### PR TITLE
Issue about not showing correct Data for moon is fixed and added Moon as default object,if entered object is not in the database.

### PR DESCRIPTION
**Pull request by rtanmay**
Added comments to make program more readable.Also updated and added status when object is just within 10 degrees from the Horizon

Solved Issue #5

### CODE REVIEW

**Comment by rtanmay** [comment]
Fixed the bug,
This the correct statement to get the time
place.date = datetime.now().strftime('%Y/%m/%d %H:%M:%S')

otherwise earlier time was 00:00:00 so the Data was not shown correct

~~Solved Issue #4~~

**Comment by shreyasbapat** [comment]
The Time thing was not needed. The data shown was correct and was getting updated every second. Because ephem.now() manages it. :)

**Comment by rtanmay** [comment]
Then what's the point of using strftime() if we have ephem.now()?

Also, which object does it give details about when we enter any random name?
I thought it was not mentioned in the code, so I made it the Moon.
Please correct me if I am wrong.

Thanks

**Comment by shreyasbapat** [comment]
Yeah, that I have not looked up for. I am merging this. Now for time, ephem.now() gets the time. But the date has to be given in format of YY/M/D Hence I used it to format the date output.

**Pull request merged**
